### PR TITLE
chore: add dependabot config

### PR DESCRIPTION
**Pull request by sam-github**
Greenkeeper is being sunset.

See: https://github.ibm.com/runtimes/squad-node/issues/635

### CODE REVIEW

**Comment by sam-github** [comment]
Actually, other than the README update, I don't know if the config is needed, it seems to be the default behaviour if the repo is added via the dependabot UI: https://app.dependabot.com/accounts/CloudNativeJS

**Comment by richardlau** [comment]
The test file changes are unrelated?

**Comment by sam-github** [comment]
The test files appear to change as a side-effect of running `npm test`. Thats pretty messed up. I didn't notice, I'll back them out.

**Review by richardlau — APPROVED** [review]

**Comment by BethGriggs** [comment]
@sam-github, it's possible that the test changes were due to a TypeScript related dependency update. I cannot see what the changes were, but I think it's possibility.

`npm test` runs a TypeScript build, so if there's any change in the TypeScript output then `npm test` will cause changes in the generated files.

**Pull request merged**
