### PR TITLE
Don't publish *.ts source files to NPM

### PR DESCRIPTION
**Pull request by jacobwgillespie**
After adding this module as a dependency, my TypeScript build is now failing as I have `noUnusedParameters` enabled in my `tsconfig.json`. This occurs because `tsc` is resolving files inside `@cloudnative/health-connect` to the `.ts` files that are included in the NPM package _first_ before the `.d.ts`, so `skipLibCheck` has no effect. This means that _my_ `tsconfig.json` rules are applied to this module's files as if they were my source.

---

This PR adds a `.npmignore` file to exclude plain `.ts` files from the published module.

You can see the difference by running `npm publish --dry-run` with and without this file.

---

The errors when running `tsc` look like this:

```console
$ tsc

node_modules/@cloudnative/health-connect/src/connect-cloud-health/ConnectHealth.ts:28:53 - error TS6133: 'req' is declared but its value is never read.

28     let middleware = <NextHandleFunction> function (req: http.IncomingMessage, res: http.ServerResponse, next: NextFunction) {
                                                       ~~~

node_modules/@cloudnative/health-connect/src/connect-cloud-health/ConnectHealth.ts:28:106 - error TS6133: 'next' is declared but its value is never read.

28     let middleware = <NextHandleFunction> function (req: http.IncomingMessage, res: http.ServerResponse, next: NextFunction) {
                                                                                                            ~~~~

node_modules/@cloudnative/health-connect/src/connect-cloud-health/ConnectHealth.ts:41:17 - error TS6133: 'err' is declared but its value is never read.

41         .catch((err) => {res.end()})
                   ~~~

```

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
I have also opened https://github.com/CloudNativeJS/cloud-health/pull/63 to fix this issue in `cloud-health`. I'm currently not getting any TypeScript errors from that project, but it has the similar issue where it's shipping `.ts` source files, which TypeScript is evaluating like it's my project's source.

**Comment by jacobwgillespie** [comment]
For now, I'm working around this issue with a `postinstall` script, in case anyone else is experiencing the same error:

**package.json**

```javascript
{
  "scripts": {
    "postinstall": "./postinstall.sh"
  }
}
```

**postinstall.sh**

```sh
#!/bin/sh
set -eu

rm node_modules/@cloudnative/health-connect/src/connect-cloud-health/ConnectHealth.ts || true
```

**Comment by jacobwgillespie** [comment]
Friendly ping, @sam-github, would you be able to take a look at this PR and https://github.com/CloudNativeJS/cloud-health/pull/63? Thanks!

**Comment by sam-github** [comment]
@jacobwgillespie Sorry, I am no longer an org member so I've no more access than you (and no involvement in the project).

**Comment by jacobwgillespie** [comment]
No worries, thanks for the quick reply!

Friendly ping to @BethGriggs and @andrewhughes101 then 🙂

**Pull request closed without merging**
